permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Gavin Gao
  email: gaojing2356@163.com
  link: 
  weibo: 
  github: http://github.com/gaojing2016
  music: 
  linkedin: 

# 站点信息
title: gaojing2016的博客
description: My personal blog
url: 
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id:  
  url: 

# disqus 设置
disqus:
  shortname: gavin

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
